services:
  mimi3:
    build:
      context: .
    image: mimi3:hf_latest
    container_name: mimi3
    init: true
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-7860}:${SERVER_PORT:-7860}"
    volumes:
      - ./users:/app/users
      - ./logs:/app/logs
      - ./data:/app/data
